
using System.Text.Json.Serialization;

namespace DTO.Response.Report
{
    public class ClientResponseDto
    {
        public int Id { get; set; }
        public int locationId { get; set; }
        public string locationName { get; set; }
        public string cad_number { get; set; }
        public string call_type { get; set; }
        public DateTime? cad_date { get; set; }
        public string agency_segment { get; set; }
        public string call_status { get; set; }
        public string caller_id { get; set; }
        public string caller_number { get; set; }
        public string callback_number { get; set; }
        public string hebrew_name { get; set; }
        public int? contact_id { get; set; }
        public int? callLocationId { get; set; }
        public string pickup_address { get; set; }
        public string pickup_address_filtered { get; set; }
        public string street { get; set; }
        public string pickup_city { get; set; }
        public string pickup_state { get; set; }
        public string pickup_zip { get; set; }
        public string cross1 { get; set; }
        public string cross2 { get; set; }
        public string cross_street { get; set; }
        public string cross_street2 { get; set; }
        public string area { get; set; }
        public string Hospital { get; set; }
        public int? hospitalId { get; set; }
        public decimal? HospitalLatitude { get; set; }
        public decimal? HospitalLongitude { get; set; }
        public string hospitalNickname { get; set; }
        public string buses { get; set; }
        public string unitsStr { get; set; }
        public string medicsStr { get; set; }
        public string driversStr { get; set; }
        public string unitsSceneOnlyStr { get; set; }
        public List<MembersResponseDto> units { get; set; }
        public List<MembersResponseDto> medics { get; set; }
        public List<MembersResponseDto> drivers { get; set; }
        public List<MembersResponseDto> unitsSceneOnly { get; set; }
        public List<string> nonExistentDriversOnDb { get; set; }
        public List<string> nonExistentMedicsOnDb { get; set; }
        public List<string> nonExistentUnitsOnDb { get; set; }
        public List<string> nonExistentUnitOnScenesOnDb { get; set; }
        public List<string> nonExistentIsBusesOnDb { get; set; }
        public List<MembersResponseDto> isBusMember { get; set; }
        public string family_last_name { get; set; }
        public string family_first_name { get; set; }
        public string pt_last_name { get; set; }
        public string pt_first_name { get; set; }
        public string parent_name { get; set; }
        public string pt_age { get; set; }
        public string pt_Gender { get; set; }
        public decimal? pickup_latitude { get; set; }
        public decimal? pickup_longitude { get; set; }
        public string access { get; set; }
        public string Gps_Link { get; set; }
        public string message { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? max_member_count { get; set; }
        public int? max_als_count { get; set; }
        public int? max_driver_count { get; set; }
        public bool is_notification_sent { get; set; }
        public string external_file_name { get; set; }
        public string callInfoText { get; set; }

        [JsonIgnore]
        public HashSet<MembersResponseDto> AllMemberSet { get; set; }

        public string dismissed_event { get; set; }
        public string cancellation_reason { get; set; }
        public string line { get; set; }
        public string call_location { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string phone4 { get; set; }
        public string phone5 { get; set; }
        public string phone6 { get; set; }
        public bool isCode1 { get; set; }
        public bool is3rdPartyCall { get; set; }
        public bool isContactAddressSet { get; set; }
        public string contactFormattedAddress1 { get; set; }
        public string contactAddress1Street { get; set; }
        public string YearMonthDayPartOfAge { get; set; }
        public string assignedTime { get; set; }
        public string enRouteTime { get; set; }
        public string onSceneTime { get; set; }
        public string fromSceneTime { get; set; }
        public string destinationTime { get; set; }
        public string inServiceTime { get; set; }
        public string backHomeTime { get; set; }
        public string pdDispatchedTime { get; set; }
        public string alsDispatchedTime { get; set; }
        public ClientAcceptableCounts clientAcceptableCounts { get; set; }
        public bool hasMessage { get; set; }
        public bool isFromApp { get; set; }
        public bool isFromTextMessage { get; set; }
        public int? forSceneNumber { get; set; }
        public int? forBusNumber { get; set; }
        public DateTime? replyTextCreatedDate { get; set; }
        public string createdBy { get; set; }
        public bool isCovered { get; set; }
        public bool? isMemberActivePhone { get; set; }
        public string relatedMemberBadgeNumber { get; set; }
        public string relatedMemberName { get; set; }
        public string relatedMemberAddress { get; set; }
        public string relatedMemberId { get; set; }
        public bool isPickup { get; set; }
        public bool useCallback { get; set; }
        public string optValues { get; set; }
        public bool shareWithMembers { get; set; }
        public bool? isHwy { get; set; }
        public string callStatusColor { get; set; }
        public string note { get; set; }
        public bool? pd { get; set; }
        public string zipArea { get; set; }
        public string areaCity { get; set; }
        public bool? isPlacePhone { get; set; }
        public string relatedPlaceName { get; set; }
        public string relatedPlaceAddress { get; set; }
        public int? relatedPlaceId { get; set; }
        public string localCadNumber { get; set; }
        public string mappedCallStatus { get; set; }
        public bool isCallStatusManual { get; set; }
        public bool pcrOn { get; set; }
        public bool isTransferred { get; set; }
        public bool isAcknowledged { get; set; }
        public int? transferredFrom { get; set; }
        public int? transferredTo { get; set; }
        public string transferId { get; set; }
    }
}
